version: '3'
services:
  fontend:
    stdin_open: true
    tty: true
    container_name: frontend-react-tempestgaming
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules